### ISSUE TITLE
Run shoryuken-later and shoryuken?

### ISSUE THREAD

**Issue by farski** [joekhoobyar/shoryuken-later#5]
Just to make sure I'm understanding this right...

I have an existing setup that is a Rails app and a shoryuken process to consume messages. If I want to keep all that working, but add shoryuken-later, I would need to have both shoryuken-later and shoryuken processes running, right?

(i.e., all shoryuken-later is doing is polling for delayed messages; it won't actually consumer anything on the SQS queue, correct?)

**Comment by joekhoobyar** [comment]
Yes, both processes need to be running.  See the wiki for a Capistrano recipe that will do that automatically.  Also, it does _not_ consume anything on the queue.

Lastly, if I implement #3, then we won't need separate process.

**Comment by farski** [comment]
Cool, thanks. I'm working on getting this all running in Docker containers, so separate processes isn't necessarily a bad thing for me.
